@base_url = https://localhost:7200/

# FUNCIONÁRIO ######################################

### Criação de um novo funcionário
POST  https://localhost:7200/api/funcionario/cadastrar
Content-Type: application/json

{
    "Nome": "Seu nome",
    "Cpf" : "12345678912",
    "email": "test"
}

### Obtenção de todos os funcionários
GET https://localhost:7200/api/funcionario/Listar

# FOLHA ############################################

### Criação de uma nova folha
POST https://localhost:7200/api/folha/create
Content-Type: application/json

{
    "valor": 50,
    "quantidade" : 1000,
    "mes" : 10,
    "ano" : 2023,
    "funcionarioId" : 1
}

### Obtenção de todas as folhas
GET https://localhost:7200/api/folha/listar

### Obtenção de uma folha

### Filtrar folhas por mês e ano
GET https://localhost:7200/api/folha/buscar/12345678912/10/2023